FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gcc build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY trinomial.c .
COPY trinomial.h .
COPY api.py .
COPY requirements.txt .

RUN gcc -shared -fPIC trinomial.c -o trinomial_model.so -lm

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
